# postgresql-data-only
postgresqldataonly:
  build: ./postgresql-data-only
  command: tailf /dev/null

# # Base image for orgpostgresql
postgresqlbase:
   build: ./postgresql-base
   environment:
    POSTGRES_SUPER_USER: postgres
    POSTGRES_SUPER_PASSWORD: postgres
   ports:
    - "5432:5432"
   volumes_from:
    - postgresqldataonly

postgresqlrun:
  build: ./postgresql-run
  environment:
   POSTGRES_SUPER_USER: postgres
   POSTGRES_SUPER_PASSWORD: postgres
   ORG_DB_NAME: app1
   ORG_DB_USER: app1
   ORG_DB_PASS: app1
   ORG_NAME: app1
  ports:
   - "5432:5432"
  volumes_from:
   - postgresqldataonly
  restart: always