# postgresql-data-only
dataonly:
  build: ./postgresql-data-only
  command: tailf /dev/null

# # Base image for orgpostgresql
base:
   build: ./postgresql-base
   environment:
    POSTGRES_SUPER_USER: postgres
    POSTGRES_SUPER_PASSWORD: postgres
   ports:
    - "5432:5432"
   volumes_from:
    - dataonly